package main

import (
	"encoding/json"
	"net/http"
	"time"

	"github.com/deanhattenhauer/chirpy/internal/auth"
	"github.com/deanhattenhauer/chirpy/internal/database"
	"github.com/google/uuid"
)

// User is the API representation of a Chirpy user.
// Mapped from database.User to control JSON key names via struct tags.
// Keeping this separate from the database model allows the API shape
// to evolve independently of the database schema.
type User struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Email     string    `json:"email"`
}

// handlerCreateUser creates a new user account with the provided email.
// Returns 201 Created with the full user object on success.
func (cfg *apiConfig) handlerCreateUser(w http.ResponseWriter, r *http.Request) {
	// parameters defines the expected shape of the request body.
	type parameters struct {
		Password string `json:"password"`
		Email string `json:"email"`
	}

	// Decode the request body — returns 500 if JSON is malformed or wrong types.
	decoder := json.NewDecoder(r.Body)
	params := parameters{}
	err := decoder.Decode(&params)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't decode parameters", err)
		return
	}
	
	hash, err := auth.HashPassword(params.Password)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't hash password", err)
		return
	}

	// Persist the user to the database — ID and timestamps are generated by Postgres.
	user, err := cfg.dbQueries.CreateUser(r.Context(), database.CreateUserParams{HashedPassword: hash, Email: params.Email})
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't create user", err)
		return
	}

	// Map database.User to the API User struct before responding.
	// This decouples the JSON response shape from the internal database model.
	respondWithJSON(w, http.StatusCreated, User{
		ID:        user.ID,
		CreatedAt: user.CreatedAt,
		UpdatedAt: user.UpdatedAt,
		Email:     user.Email,
	})
}